import torch
import matplotlib.pyplot as plt


def inf_train_gen(n_grid_points: int = 128, batch_size: int = 200, device: str = "cpu") -> torch.Tensor:
    assert n_grid_points % 4 == 0, "number of grid points has to be divisible by 4"
    n_grid_points = n_grid_points // 4

    x1 = torch.randint(low=0, high=n_grid_points * 4, size=(batch_size,), device=device)
    samples_x2 = torch.randint(low=0, high=n_grid_points, size=(batch_size,), device=device)

    x2 = (
            samples_x2
            + 2 * n_grid_points
            - torch.randint(low=0, high=2, size=(batch_size,), device=device) * 2 * n_grid_points
            + (torch.floor(x1 / n_grid_points) % 2) * n_grid_points
    )

    x_end = 1.0 * torch.cat([x1[:, None], x2[:, None]], dim=1)
    return x_end.long()


# 生成数据
data = inf_train_gen(n_grid_points=128, batch_size=1000, device="cpu")
x = data[:, 0].numpy()
y = data[:, 1].numpy()

# 可视化
plt.figure(figsize=(10, 10))
plt.scatter(x, y, s=10, alpha=0.6, c='blue', edgecolors='white')
plt.title("Grid-like Data Distribution Generated by inf_train_gen")
plt.xlabel("X1 (Grid Columns)")
plt.ylabel("X2 (Grid Rows)")
plt.grid(True, linestyle='--', alpha=0.5)
plt.xticks(range(0, 128, 16))
plt.yticks(range(0, 128, 16))
plt.xlim(0, 128)
plt.ylim(0, 128)
plt.gca().set_aspect('equal')  # 保持坐标轴比例一致
plt.show()